services:
  appbuild:
    build:
      context: .
      dockerfile: Dockerfile.conan
    network_mode: host
    environment:
    - CMAKE_BUILD_PARALLEL_LEVEL=8
    command: ./build_conan.sh
    volumes:
      - ./:/build

  apprun:
    build:
      context: .
    network_mode: host

