name: client-go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.20.10
    - run: >
        cd go &&
        go build -buildvcs=false ./...

